# Operation test

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## Torch.topk

In [2]:
output = torch.tensor([[-5.415, 0.4227],
                           [-4.2153, -0.4337],
                           [-0.1972, -5.1387],
                           [-0.1829, -4.9819]])

In [3]:
maxk = max((1,))
_, pred = output.topk(maxk, 1, True, True)

In [4]:
_

tensor([[ 0.4227],
        [-0.4337],
        [-0.1972],
        [-0.1829]])

In [5]:
pred

tensor([[1],
        [1],
        [0],
        [0]])

## Torch.cat

In [6]:
a = torch.ones([1, 3])
b = torch.zeros([1, 2])
c = torch.zeros([1, 3])
print("a:",a)
print("b:",b)
print("b:",c)

a: tensor([[1., 1., 1.]])
b: tensor([[0., 0.]])
b: tensor([[0., 0., 0.]])


In [7]:
print(torch.cat([a, b], 1))

tensor([[1., 1., 1., 0., 0.]])


In [8]:
print(torch.cat([a, c], 0))

tensor([[1., 1., 1.],
        [0., 0., 0.]])


## LocalResponseNorm
Check here : https://github.com/pytorch/pytorch/blob/dcfc121fd792393205104a9f07fc4ee0da0ced69/torch/nn/modules/normalization.py#L10

In [9]:
lrn = nn.LocalResponseNorm(2)
signal_2d = torch.randn(2, 2, 2, 4)
output_2d = lrn(signal_2d)

In [10]:
print("signal_2d:",signal_2d)
print("\nAfter ...\n")
print("output_2d:",output_2d)

signal_2d: tensor([[[[ 0.7326,  0.2788,  0.8947,  1.4366],
          [ 1.6765,  1.3023, -1.6579,  0.1953]],

         [[-0.3328, -0.9956, -0.9203,  1.5893],
          [-0.4099, -0.8439, -0.1187, -0.1558]]],


        [[[ 1.3138, -0.4992,  0.3741, -0.0366],
          [ 0.7841,  1.9723,  1.6017, -0.5818]],

         [[-0.3153,  0.3414, -1.5202, -1.2288],
          [-0.8745, -1.0803,  1.4397, -0.9804]]]])

After ...

output_2d: tensor([[[[ 0.7326,  0.2788,  0.8946,  1.4365],
          [ 1.6763,  1.3022, -1.6577,  0.1953]],

         [[-0.3328, -0.9956, -0.9202,  1.5890],
          [-0.4099, -0.8439, -0.1187, -0.1558]]],


        [[[ 1.3137, -0.4992,  0.3741, -0.0366],
          [ 0.7841,  1.9720,  1.6015, -0.5818]],

         [[-0.3152,  0.3414, -1.5200, -1.2288],
          [-0.8745, -1.0801,  1.4394, -0.9804]]]])


In [11]:
output_2d_norm = torch.nn.functional.local_response_norm(signal_2d, 2, alpha=0.0001, beta=0.75, k=1.0)
output_2d_norm

tensor([[[[ 0.7326,  0.2788,  0.8946,  1.4365],
          [ 1.6763,  1.3022, -1.6577,  0.1953]],

         [[-0.3328, -0.9956, -0.9202,  1.5890],
          [-0.4099, -0.8439, -0.1187, -0.1558]]],


        [[[ 1.3137, -0.4992,  0.3741, -0.0366],
          [ 0.7841,  1.9720,  1.6015, -0.5818]],

         [[-0.3152,  0.3414, -1.5200, -1.2288],
          [-0.8745, -1.0801,  1.4394, -0.9804]]]])