# Operation test

In [1]:
import torch

## Torch.topk

In [2]:
output = torch.tensor([[-5.415, 0.4227],
                           [-4.2153, -0.4337],
                           [-0.1972, -5.1387],
                           [-0.1829, -4.9819]])

In [3]:
maxk = max((1,))  # 取top1准确率，若取top1和top5准确率改为max((1,5))
_, pred = output.topk(maxk, 1, True, True)

In [4]:
_

tensor([[ 0.4227],
        [-0.4337],
        [-0.1972],
        [-0.1829]])

In [5]:
pred

tensor([[1],
        [1],
        [0],
        [0]])

## Torch.cat

In [6]:
a = torch.ones([1, 3])
b = torch.zeros([1, 2])
c = torch.zeros([1, 3])
print("a:",a)
print("b:",b)
print("b:",c)

a: tensor([[1., 1., 1.]])
b: tensor([[0., 0.]])
b: tensor([[0., 0., 0.]])


In [7]:
print(torch.cat([a, b], 1))

tensor([[1., 1., 1., 0., 0.]])


In [8]:
print(torch.cat([a, c], 0))

tensor([[1., 1., 1.],
        [0., 0., 0.]])
