In [2]:
import torch 
print(torch.cuda.is_available())
print(torch.rand(2,2))

True
tensor([[0.0406, 0.5329],
        [0.9292, 0.2647]])


# Tensor Method

In [3]:
x = torch.tensor([[1,2,3],[2,3,4],[3,4,5]])
x

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [4]:
x[0][0] = 4
x

tensor([[4, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

# .Zeros() and .ones()


In [5]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [6]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

# .item()

In [7]:
torch.ones(3,2)+ torch.ones(3,2)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [13]:
A = torch.rand(1)
A

tensor([0.4345])

In [14]:
A.item()

0.43449127674102783

# .device

In [15]:
A.device

device(type='cpu')

# Change the device from CPU to GPU

In [0]:
A_GPU = A.to("cuda")

In [18]:
A_GPU.device

device(type='cuda', index=0)

# Tensor Operations


In [23]:
B = torch.rand(3,3)
print("B :",B)
print("B.max() :",B.max())

B : tensor([[0.1645, 0.2849, 0.2653],
        [0.9675, 0.6427, 0.3756],
        [0.5397, 0.9079, 0.0162]])
B.max() : tensor(0.9675)


In [26]:
print("B.max().item() :",B.max().item())

B.max().item() : 0.9675191640853882


# Change the type

In [27]:
LongType = torch.tensor([[1,2,3],[2,3,4],[3,4,5]])
LongType

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

## .type()

In [28]:
LongType.type()

'torch.LongTensor'

In [30]:
ShortType = LongType.to(dtype = torch.float32)
ShortType

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])

In [31]:
ShortType.type()

'torch.FloatTensor'

# underscore(_)

In [0]:
C = torch.rand(3,3)

In [34]:
C.log2()

tensor([[-4.3960, -2.0984, -0.8201],
        [-3.8324, -8.1745, -0.5909],
        [-0.5238, -3.0697, -1.5849]])

In [35]:
C.log2_()

tensor([[-4.3960, -2.0984, -0.8201],
        [-3.8324, -8.1745, -0.5909],
        [-0.5238, -3.0697, -1.5849]])

# Reshape() VS view(), and contiguous()

In [0]:
flat = torch.rand(784)

In [38]:
viewed_tensor = flat.view(1,28,28)
viewed_tensor.shape

torch.Size([1, 28, 28])

In [39]:
reshaped_tensor = flat.reshape(1,28,28)
reshaped_tensor.shape

torch.Size([1, 28, 28])

if you use reshape funciton, you have to have the same number of total elements as the original. 
```
1*28*28 == 784
```

Maybe we could say 
```
tensor.reshape() = tensor.contiguous().view()
```

# permute()

In [44]:
D = torch.rand(1,28,28)
D.shape

torch.Size([1, 28, 28])

In [0]:
E = D.permute(2,1,0)

In [48]:
E.shape

torch.Size([28, 28, 1])

This function is quite convenient!!

**Another thing should be carefule about that pytorch perfers to deal with tensor in a [channel, height, width].
It is different with Tensorflow.**