In [1]:
import numpy as np

# np.tile

### a

In [2]:
a = np.array([0, 1, 2])

In [3]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [4]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [5]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

### b

In [6]:
b = np.array([[1, 2], [3, 4]])

In [7]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [8]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### c

In [9]:
c = np.array([1,2,3,4])

In [10]:
np.tile(c,(4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

# np.clip

In [11]:
x=np.array([1,2,3,5,6,7,8,9])

In [12]:
np.clip(x,3,8)

array([3, 3, 3, 5, 6, 7, 8, 8])

In [13]:
x=np.array([[1,2,3,5,6,7,8,9],[1,2,3,5,6,7,8,9]])

In [14]:
np.clip(x,3,8)

array([[3, 3, 3, 5, 6, 7, 8, 8],
       [3, 3, 3, 5, 6, 7, 8, 8]])