# Operation test

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## Torch.topk

In [2]:
output = torch.tensor([[-5.415, 0.4227],
                           [-4.2153, -0.4337],
                           [-0.1972, -5.1387],
                           [-0.1829, -4.9819]])

In [3]:
maxk = max((1,))
_, pred = output.topk(maxk, 1, True, True)

In [4]:
_

tensor([[ 0.4227],
        [-0.4337],
        [-0.1972],
        [-0.1829]])

In [5]:
pred

tensor([[1],
        [1],
        [0],
        [0]])

## Torch.cat

In [6]:
a = torch.ones([1, 3])
b = torch.zeros([1, 2])
c = torch.zeros([1, 3])
print("a:",a)
print("b:",b)
print("b:",c)

a: tensor([[1., 1., 1.]])
b: tensor([[0., 0.]])
b: tensor([[0., 0., 0.]])


In [7]:
print(torch.cat([a, b], 1))

tensor([[1., 1., 1., 0., 0.]])


In [8]:
print(torch.cat([a, c], 0))

tensor([[1., 1., 1.],
        [0., 0., 0.]])


## LocalResponseNorm
Check here : https://github.com/pytorch/pytorch/blob/dcfc121fd792393205104a9f07fc4ee0da0ced69/torch/nn/modules/normalization.py#L10

In [9]:
lrn = nn.LocalResponseNorm(2)
signal_2d = torch.randn(2, 2, 2, 4)
output_2d = lrn(signal_2d)

In [10]:
print("signal_2d:",signal_2d)
print("\nAfter ...\n")
print("output_2d:",output_2d)

signal_2d: tensor([[[[-1.5643e+00, -4.3870e-01,  8.5277e-01, -6.0350e-04],
          [ 1.3841e+00, -1.4011e+00,  1.4052e+00,  2.2986e+00]],

         [[-6.3327e-01, -1.9680e+00,  1.5284e-01,  1.4171e+00],
          [-2.3226e-01,  7.0436e-01, -3.4351e-01,  1.8439e-01]]],


        [[[ 8.0034e-01, -5.4223e-01, -3.6704e-01, -1.0008e+00],
          [-7.3729e-01, -1.1249e+00, -6.7643e-01, -2.2108e+00]],

         [[ 2.1660e+00, -1.2783e-01, -1.0032e+00,  7.4064e-01],
          [ 4.0207e-01, -1.1306e+00,  1.9505e+00,  2.2488e-01]]]])

After ...

output_2d: tensor([[[[-1.5641e+00, -4.3870e-01,  8.5275e-01, -6.0350e-04],
          [ 1.3840e+00, -1.4010e+00,  1.4051e+00,  2.2981e+00]],

         [[-6.3320e-01, -1.9677e+00,  1.5284e-01,  1.4170e+00],
          [-2.3224e-01,  7.0429e-01, -3.4348e-01,  1.8435e-01]]],


        [[[ 8.0032e-01, -5.4222e-01, -3.6704e-01, -1.0008e+00],
          [-7.3727e-01, -1.1248e+00, -6.7642e-01, -2.2104e+00]],

         [[ 2.1656e+00, -1.2783e-01, -1.0032e+00,  

In [11]:
output_2d_norm = torch.nn.functional.local_response_norm(signal_2d, 2, alpha=0.0001, beta=0.75, k=1.0)
output_2d_norm

tensor([[[[-1.5641e+00, -4.3870e-01,  8.5275e-01, -6.0350e-04],
          [ 1.3840e+00, -1.4010e+00,  1.4051e+00,  2.2981e+00]],

         [[-6.3320e-01, -1.9677e+00,  1.5284e-01,  1.4170e+00],
          [-2.3224e-01,  7.0429e-01, -3.4348e-01,  1.8435e-01]]],


        [[[ 8.0032e-01, -5.4222e-01, -3.6704e-01, -1.0008e+00],
          [-7.3727e-01, -1.1248e+00, -6.7642e-01, -2.2104e+00]],

         [[ 2.1656e+00, -1.2783e-01, -1.0032e+00,  7.4060e-01],
          [ 4.0206e-01, -1.1305e+00,  1.9502e+00,  2.2484e-01]]]])