# Operation test

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

## Torch.topk

In [2]:
output = torch.tensor([[-5.415, 0.4227],
                           [-4.2153, -0.4337],
                           [-0.1972, -5.1387],
                           [-0.1829, -4.9819]])

In [3]:
maxk = max((1,))
_, pred = output.topk(maxk, 1, True, True)

In [4]:
_

tensor([[ 0.4227],
        [-0.4337],
        [-0.1972],
        [-0.1829]])

In [5]:
pred

tensor([[1],
        [1],
        [0],
        [0]])

## Torch.cat

In [6]:
a = torch.ones([1, 3])
b = torch.zeros([1, 2])
c = torch.zeros([1, 3])
print("a:",a)
print("b:",b)
print("b:",c)

a: tensor([[1., 1., 1.]])
b: tensor([[0., 0.]])
b: tensor([[0., 0., 0.]])


In [7]:
print(torch.cat([a, b], 1))

tensor([[1., 1., 1., 0., 0.]])


In [8]:
print(torch.cat([a, c], 0))

tensor([[1., 1., 1.],
        [0., 0., 0.]])


## LocalResponseNorm
Check here : https://github.com/pytorch/pytorch/blob/dcfc121fd792393205104a9f07fc4ee0da0ced69/torch/nn/modules/normalization.py#L10

In [9]:
lrn = nn.LocalResponseNorm(2)
signal_2d = torch.randn(2, 2, 2, 4)
output_2d = lrn(signal_2d)

In [10]:
print("signal_2d:",signal_2d)
print("\nAfter ...\n")
print("output_2d:",output_2d)

signal_2d: tensor([[[[ 0.0408,  1.1338,  0.3098,  0.2453],
          [-0.8429,  0.9977,  0.9967,  0.1558]],

         [[-0.8071, -0.3961,  1.0737, -0.4210],
          [ 0.7008, -0.7149,  0.0929,  0.8093]]],


        [[[ 0.4955,  0.5864,  0.7391,  1.1015],
          [-0.4389, -1.1232,  1.8109, -0.4248]],

         [[-1.5490,  0.2501,  0.8784, -0.4013],
          [ 0.2832,  0.1359, -0.5589, -0.6184]]]])

After ...

output_2d: tensor([[[[ 0.0408,  1.1338,  0.3098,  0.2453],
          [-0.8428,  0.9976,  0.9966,  0.1558]],

         [[-0.8070, -0.3960,  1.0736, -0.4209],
          [ 0.7008, -0.7149,  0.0929,  0.8093]]],


        [[[ 0.4955,  0.5863,  0.7391,  1.1015],
          [-0.4389, -1.1231,  1.8107, -0.4248]],

         [[-1.5488,  0.2501,  0.8784, -0.4013],
          [ 0.2832,  0.1359, -0.5589, -0.6184]]]])


In [11]:
output_2d_norm = torch.nn.functional.local_response_norm(signal_2d, 2, alpha=0.0001, beta=0.75, k=1.0)
output_2d_norm

tensor([[[[ 0.0408,  1.1338,  0.3098,  0.2453],
          [-0.8428,  0.9976,  0.9966,  0.1558]],

         [[-0.8070, -0.3960,  1.0736, -0.4209],
          [ 0.7008, -0.7149,  0.0929,  0.8093]]],


        [[[ 0.4955,  0.5863,  0.7391,  1.1015],
          [-0.4389, -1.1231,  1.8107, -0.4248]],

         [[-1.5488,  0.2501,  0.8784, -0.4013],
          [ 0.2832,  0.1359, -0.5589, -0.6184]]]])

# Torch.from_numpy

In [12]:
a = np.array([1, 2, 3])

We can see that the t is converted to Tensor from np.array.

In [13]:
t = torch.from_numpy(a)
t

tensor([1, 2, 3])

If we modify the element in `t`, the `a` will also be changed.

In [14]:
t[0] = -1
a

array([-1,  2,  3])

# Torch.cuda.empty_cache()

In [15]:
device = torch.device('cuda:0')
# Define two tensors
dummy_tensor_1 = torch.randn(120, 3, 512, 512).float().to(device)  # 120*3*512*512*4/1000/1000 = 377.48M
dummy_tensor_2 = torch.randn(80, 3, 512, 512).float().to(device)  # 80*3*512*512*4/1000/1000 = 251.64M

In [16]:
# Release
dummy_tensor_1 = dummy_tensor_1.cpu()
dummy_tensor_2 = dummy_tensor_2.cpu()

torch.cuda.empty_cache()