# Operation test

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

## Torch.topk

In [2]:
output = torch.tensor([[-5.415, 0.4227],
                           [-4.2153, -0.4337],
                           [-0.1972, -5.1387],
                           [-0.1829, -4.9819]])

In [3]:
maxk = max((1,))
_, pred = output.topk(maxk, 1, True, True)

In [4]:
_

tensor([[ 0.4227],
        [-0.4337],
        [-0.1972],
        [-0.1829]])

In [5]:
pred

tensor([[1],
        [1],
        [0],
        [0]])

## Torch.cat

In [6]:
a = torch.ones([1, 3])
b = torch.zeros([1, 2])
c = torch.zeros([1, 3])
print("a:",a)
print("b:",b)
print("b:",c)

a: tensor([[1., 1., 1.]])
b: tensor([[0., 0.]])
b: tensor([[0., 0., 0.]])


In [7]:
print(torch.cat([a, b], 1))

tensor([[1., 1., 1., 0., 0.]])


In [8]:
print(torch.cat([a, c], 0))

tensor([[1., 1., 1.],
        [0., 0., 0.]])


## LocalResponseNorm
Check here : https://github.com/pytorch/pytorch/blob/dcfc121fd792393205104a9f07fc4ee0da0ced69/torch/nn/modules/normalization.py#L10

In [9]:
lrn = nn.LocalResponseNorm(2)
signal_2d = torch.randn(2, 2, 2, 4)
output_2d = lrn(signal_2d)

In [10]:
print("signal_2d:",signal_2d)
print("\nAfter ...\n")
print("output_2d:",output_2d)

signal_2d: tensor([[[[ 0.4992,  1.2629, -0.0082,  0.4857],
          [ 0.0188,  0.2765, -0.4137,  1.1556]],

         [[ 0.7359,  1.3797, -0.3224, -0.8392],
          [-0.7564, -1.1753,  1.1643,  0.0586]]],


        [[[ 0.0375,  0.3952,  0.3483, -0.5367],
          [-0.6039, -1.7000, -1.0310, -0.2094]],

         [[ 0.3887,  0.1753, -1.2007, -0.3255],
          [ 0.9617,  1.1281,  0.1411,  0.1444]]]])

After ...

output_2d: tensor([[[[ 0.4992,  1.2628, -0.0082,  0.4857],
          [ 0.0188,  0.2765, -0.4137,  1.1555]],

         [[ 0.7358,  1.3796, -0.3224, -0.8391],
          [-0.7564, -1.1752,  1.1643,  0.0586]]],


        [[[ 0.0375,  0.3952,  0.3483, -0.5367],
          [-0.6039, -1.6998, -1.0309, -0.2094]],

         [[ 0.3887,  0.1753, -1.2006, -0.3255],
          [ 0.9616,  1.1279,  0.1411,  0.1444]]]])


In [11]:
output_2d_norm = torch.nn.functional.local_response_norm(signal_2d, 2, alpha=0.0001, beta=0.75, k=1.0)
output_2d_norm

tensor([[[[ 0.4992,  1.2628, -0.0082,  0.4857],
          [ 0.0188,  0.2765, -0.4137,  1.1555]],

         [[ 0.7358,  1.3796, -0.3224, -0.8391],
          [-0.7564, -1.1752,  1.1643,  0.0586]]],


        [[[ 0.0375,  0.3952,  0.3483, -0.5367],
          [-0.6039, -1.6998, -1.0309, -0.2094]],

         [[ 0.3887,  0.1753, -1.2006, -0.3255],
          [ 0.9616,  1.1279,  0.1411,  0.1444]]]])

# Torch.from_numpy

In [12]:
a = np.array([1, 2, 3])

We can see that the t is converted to Tensor from np.array.

In [13]:
t = torch.from_numpy(a)
t

tensor([1, 2, 3])

If we modify the element in `t`, the `a` will also be changed.

In [14]:
t[0] = -1
a

array([-1,  2,  3])

# Torch.cuda.empty_cache()

In [15]:
device = torch.device('cuda:0')
# Define two tensors
dummy_tensor_1 = torch.randn(120, 3, 512, 512).float().to(device)  # 120*3*512*512*4/1000/1000 = 377.48M
dummy_tensor_2 = torch.randn(80, 3, 512, 512).float().to(device)  # 80*3*512*512*4/1000/1000 = 251.64M

In [16]:
# Release
dummy_tensor_1 = dummy_tensor_1.cpu()
dummy_tensor_2 = dummy_tensor_2.cpu()

torch.cuda.empty_cache()

# named_children & named_modules
source: https://blog.csdn.net/watermelon1123/article/details/98036360

In [17]:
class TestModule(nn.Module):
    def __init__(self):
        super(TestModule,self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(16,32,3,1),
            nn.ReLU(inplace=True)
        )
        self.layer2 = nn.Sequential(nn.Linear(32,10))
        
    def forward(self,x):
        x = self.layer1(x)
        x = self.layer2(x)

In [18]:
model = TestModule()
 
for name, module in model.named_children():
    print('children module:', name)

children module: layer1
children module: layer2


In [19]:
for name, module in model.named_modules():
    print('modules:', name)

modules: 
modules: layer1
modules: layer1.0
modules: layer1.1
modules: layer2
modules: layer2.0


# view funtion with -1

In [20]:
a = torch.arange(1, 17)  # a's shape is (16,)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [21]:
a.view(4, 4) # output below

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [22]:
a.view(2, 2, 4) # output below

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]])

In [23]:
print("a.size(0)",a.size(0))
a.view(a.size(0), -1)

a.size(0) 16


tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16]])